### ISSUE TITLE
Trouble with file paths

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#8]
I'm not sure if braingames/base/finders.py has been written for GameFinder to look in each game's specific /static/ folder or if it just uses the first one that it finds.

Once I got my local dev env to work I couldn't get shrub/game.js to load anything but the old version of jsPsych from the other game's folder. I had to delete the old folders for it to read the new files.

**Comment by glogiotatidis** [comment]
`GameFinder` collects all statics from all games. To link to a static from a game you should use `gamestatic` helper (e.g https://github.com/mozilla/braingames/blob/master/games/example-game-2/game.jinja#L6) You can still use the `static` helper since nodoby prevents you from linking games and statics from different games but you probably don't want to do that.

I added another game [example-game-2](https://github.com/mozilla/braingames/tree/master/games/example-game-2) to demonstrate how this executes different JS from its own folder. 

If your problem persists please pull request the code so we can debug further

**Comment by glogiotatidis** [comment]
* https://moz-braingames-stage.herokuapp.com/game/example-game-2/
* https://moz-braingames-stage.herokuapp.com/game/example-game-custom-js/

**Comment by jtg567** [comment]
I definitely had my study set up with proper file/folder order, to no avail.

Up to the point that I edited the code to use the braingames templates it was at least loading the first screen working locally with `python -m SimpleHTTPServer`.

[Pushed new branch "shrub" to debug.](https://github.com/mozilla/braingames/pull/9)

**Comment by jtg567** [comment]
Osmose found problems in shrub/game.js with eslint; fixing those seemed to have remedied this issue.

**Comment by glogiotatidis** [comment]
👍
